included:
  - MediaMonksExercice/Source
excluded:
  - Pods
  - MediaMonksExercice/Source/App/AppDelegate.swift
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation

identifier_name:
  excluded:
    - id
line_length: 120
number_separator:
  minimum_length: 5

# custom_rules:
#   rule_id:
#     included: Source/SwiftLintFramework/Rules/\w+\.swift
#     name: Rule ID
#     message: Rule IDs must be all lowercase, snake case and not end with `rule`
#     regex: identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
#     severity: error
#   fatal_error:
#     name: Fatal Error
#     excluded: "Tests/*"
#     message: Prefer using `queuedFatalError` over `fatalError` to avoid leaking compiler host machine paths.
#     regex: \bfatalError\b
#     match_kinds:
#       - identifier
#     severity: error
#   rule_test_function:
#     included: Tests/SwiftLintFrameworkTests/RulesTests.swift
#     name: Rule Test Function
#     message: Rule Test Function mustn't end with `rule`
#     regex: func\s*test\w+(r|R)ule\(\)
#     severity: error